// <auto-generated />
namespace Guia4_DSE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agendamodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agendamodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202110042241125_agenda model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
